### ISSUE TITLE
Refurbishing the APBS build and CI process

### ISSUE THREAD

**Issue by intendo** [Electrostatics/apbs#163]
Modify top level CMakeLists.txt to replace External Project for building FETK.
Download FETK release compressed files.
Mimic linking in FETK like we do with NanoShaper
Update LIBRARY dependencies and INCLUDE directives.

**Comment by nsoblath** [comment]
In a major example of scope creep, work on this issue ballooned to include:
* The FETK changes mentioned above
* An alternate build for FETK using FetchContent instead of ExternalProject
* Updating the build systems for geoflow_c and pb_solvers
* Fixing bugs in geoflow_c and pb_solvers
* Changing the inclusion of TABI-PB, geoflow-c, and pb_solvers to use FetchContent instead of using ExternalProject
* Building the APBS version of TABIPBlib within the APBS build (and disabling it within TABI-PB
* Switching the automatic Windows build to use GitHub Actions instead of AppVeyor
* Refining all builds (Windows, Mac, Linux) in GitHub Actions and the `.build.sh` script

**Comment by intendo** [comment]
Are we ready to remove the Appveyor config and github action?
In other words, do we have a release that works on Windows, MacOS, and Linux?

**Comment by nsoblath** [comment]
I believe we're ready to remove the AppVeyor config.  Actually, I just pushed that change.  The GitHub Actions build now works for all three systems.

It'd be worth verifying that the built packages work for end users.  Do you have a suggestion of how to do that?  Is there a test(s) that could be run just using the built artifacts that would replicate something an end user would do?

**Comment by intendo** [comment]
I added some comments to the PR so that tests can be build and packages built. I think there are Artifacts saved in the Github Actions. We should be able to download each of the Artifacts for Windows, Mac, and Ubuntu and install them and run a few of the `examples` to see if apbs produces output.

**Comment by nsoblath** [comment]
I replied to the comments about the testing and packaging.  I'll fix the documentation about the Python version too.

I think I have enough information to attempt an application from the `examples` directory.  I'll try implementing a workflow to download the built artifacts and run an example.

**Comment by nsoblath** [comment]
Additional change now covered by this issue: iAPBS build, as discussed in #187.
