### ISSUE TITLE
Error while loading shared libraries: libpython3.9.so.1.0 

### ISSUE THREAD

**Issue by jacob-r-anderson** [Electrostatics/apbs#212]
**Describe the bug**
I downloaded APBS-3.4.0.Linux.zip. I unzipped. I renamed the directory to apbs. I then moved the directory to /home/my_name/apbs.
I edited the .bashrc to include the following.

export LD_LIBRARY_PATH=$HOME/apbs/lib:${LD_LIBRARY_PATH}
export PATH=$HOME/apbs/bin:${PATH}

When I try to run apbs I get the following error:

`apbs: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
`

My python version.
python --version
Python 3.9.10

**To Reproduce**
1. Unzip and rename APBS-3.4.0.Linux.zip to apbs 
2.  Move to $HOME.
3. Edit .bashrc to change paths
3. Run apbs

**Expected behavior**
I expected APBS to prompt for expected variables

**Screenshots**
None

**Desktop (please complete the following information):**
 - Ubuntu 18.04
-  Python 3.9.10

-None

**Additional context**
-None

**Comment by nsoblath** [comment]
The `apbs` binary is linked against a library called `libpython3.9.so.1.0`.  The error you're seeing indicates that a library with this name either isn't on your system or isn't being found.  When the release of APBS was made, we built against the same version of Python, so my guess is that we would expect your system to also have `libpython3.9.so.1.0`.  

Here are a couple things to check:
* Do you have `libpython3.9.so.1.0` on your system?  Some Python installs don't have a separately-built shared-object library.  If that's your situation, you may need to modify your Python install to build the library.
* If the library is there, is the path to it in your `LD_LIBRARY_PATH`?  Setting the path correctly should allow the library to be found.
* You can check that the library is found using `ldd /path/to/apbs`, and checking that the line with `libpython3.9.so.1.0` shows where the library has been found and does not say `not found`.

@intendo, I suggest that for the next round of updates we include statically linking against Python for Linux and Mac in the automated buidls.  This would further simplify the dependencies users have to deal with, at least on those platforms.  And the fact that static libraries are available on Linux and Mac but not Windows is already built into CMake's `findPython3` module.  So It should be as straightforward as adding a flag to the routine that finds Python.  It can be done as a CMake option for the APBS build, so that users can choose which way to build.

**Comment by intendo** [comment]
@nsoblath I vote for the static linking which is in line with the manylinux Python conventions.
