### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by rye4ray** [Electrostatics/apbs#230]
**Describe the bug**
Encountered an error when running the pre-compiled Linux version of APBS

**To Reproduce**
1. Download `APBS-3.4.0.Linux.zip` from `https://github.com/Electrostatics/apbs/releases` to my home directory
2. Unzip the file and rename the folder to `apbs`
3. Set my `LD_LIBRARY_PATH` and `PATH` environment variables
`export LD_LIBRARY_PATH=$HOME/apbs/lib:${LD_LIBRARY_PATH}
export PATH=$HOME/apbs/bin:${PATH}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.10/lib`
4. Run `apbs --help`
5. See error
apbs: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by apbs)

**Expected behavior**
Show the help option for APBS

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04.6 LTS (Bionic Beaver)

**Comment by nsoblath** [comment]
@rye4ray Thanks for your input and for your efforts that will ultimately help improve APBS.

It looks like the version of glibc that's available for Ubuntu 18.04 (2.27) is not compatible with the version that the pre-compiled version of APBS v3.4.0 was built with (2.31).  I've tested the `apbs` binary with Ubuntu 21.10 (glibc 2.34) and 22.04 (glibc 2.35), and it works in both of those cases, plus of course the Ubuntu version it was built with, 20.04.

We will probably stick with our current version of Ubuntu for the pre-compiled version of APBS, as it's difficult to try to make something compatible with every system that people want to use.  However, we do have a Dockerfile that's part of the repo that you can use immediately to build a working version of APBS within an Ubuntu 20.04 image, without having to upgrade your own system.  I recommend using the file `Dockerfile.ubuntu` that's currently in the `main` branch and will be in the upcoming release.

Your issue points to some deficiencies in the documentation, and I will take it as an action to update that documentation in order to close this issue.

**Comment by nsoblath** [comment]
Documentation updated in #231
