### ISSUE TITLE
installation issue with CUDA

### ISSUE THREAD

**Issue by PolyachenkoYA** [Electrostatics/apbs#52]
**Describe the bug**
Fails to install from conda with no real conflicts and with a strange error message.

**To Reproduce**
1. $conda create -n myenv python=3.6 && conda activate myenv
2. $conda install -c electrostatics apbs
3. 
```
Output in format: Requested package -> Available versions
The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

```
**Expected behavior**
clear installation

**Desktop (please complete the following information):**
 - OS: Fedora 30, Ununtu 18.04

**Additional context**
The problem looks similar to [this](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/55). There, the problem was in how the conda package was built and the [fix](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/55#issuecomment-629698723) came from the author himself.

**Comment by sobolevnrm** [comment]
Hello --

This is a very interesting issue since I wasn't aware we had a supported conda package for APBS! :). We do have one for PDB2PQR.  Which features are you trying to use?

If possible, it would be best if you could could install from one of our supported releases instead:  https://github.com/Electrostatics/apbs/releases

Thank you
